### ISSUE TITLE
Homebrew warns for Localazy 1.6.0 version

### ISSUE THREAD

**Issue by ilgun** [localazy/homebrew-tools#1]
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the localazy/tools tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/localazy/homebrew-tools/localazy.rb:8

And here I report folks :)

**Comment by honzabilek4** [comment]
Thanks @ilgun! This is a minor problem, I'm going to fix it though. It seems that we can safely drop that line in localazy.rb.
